import Link from "next/link";
import VantaWavesBackground from "@/components/VantaWavesBackground";

export default function Home() {
  return (
    <div className="relative overflow-hidden">
      {/* Hero Section with Vanta Waves Background */}
      <VantaWavesBackground className="min-h-screen" darkOverlay={true}>
        <section className="pt-12 pb-8 px-4 sm:px-6 lg:px-8 relative z-10">
        <div className="max-w-7xl mx-auto text-center">
          <div className="inline-flex items-center gap-2 px-4 py-2 bg-cyan-500/90 backdrop-blur-sm rounded-full text-white text-sm font-medium mb-8 border border-cyan-400">
            <span className="text-lg">🌊</span>
            Ride the Wave of Academic Success
          </div>

          <h1 className="text-5xl sm:text-6xl lg:text-7xl font-bold text-white mb-6 leading-tight drop-shadow-lg">
            Navigate Your
            <br />
            <span className="bg-gradient-to-r from-cyan-300 via-teal-300 to-emerald-300 bg-clip-text text-transparent">
              Academic Journey
            </span>
          </h1>

          <p className="text-xl text-gray-100 max-w-2xl mx-auto mb-10 drop-shadow-md">
            Set sail with the AI-powered study companion that helps you chart your course,
            weather any storm, and reach your academic destinations.
          </p>

          <div className="flex flex-col sm:flex-row gap-4 justify-center">
            <Link href="/signup" className="px-8 py-4 bg-gradient-to-r from-cyan-500 to-teal-500 text-white font-semibold rounded-xl hover:from-cyan-600 hover:to-teal-600 transition-all hover:shadow-lg hover:shadow-cyan-500/25 flex items-center justify-center gap-2 transform hover:scale-105">
              <span>⛵</span>
              Set Sail Today
              <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 7l5 5m0 0l-5 5m5-5H6" />
              </svg>
            </Link>
            <a href="#features" className="px-8 py-4 bg-white/95 backdrop-blur-sm text-gray-900 font-semibold rounded-xl hover:bg-white transition-all border border-gray-200 flex items-center justify-center gap-2 shadow-lg">
              <span>🧭</span>
              Explore Features
              <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" />
              </svg>
            </a>
          </div>
        </div>
      </section>
      </VantaWavesBackground>

      {/* Features Section - Ocean themed */}
      <section id="features" className="py-20 px-4 sm:px-6 lg:px-8 bg-white dark:bg-slate-800">
        <div className="max-w-7xl mx-auto">
          <div className="text-center mb-16">
            <span className="text-4xl mb-4 block">🏝️</span>
            <h2 className="text-3xl sm:text-4xl font-bold text-gray-900 dark:text-white mb-4">
              Discover Your Island Features
            </h2>
            <p className="text-lg text-gray-600 dark:text-gray-400 max-w-2xl mx-auto">
              Powerful tools designed to help you navigate the seas of academia and reach success.
            </p>
          </div>

          <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-8">
            {/* Feature 1 - Treasure Map */}
            <div className="group p-8 rounded-2xl bg-gradient-to-br from-cyan-50 to-teal-50 dark:from-cyan-900/20 dark:to-teal-900/20 border border-cyan-200 dark:border-cyan-800 hover:shadow-2xl hover:shadow-cyan-500/20 transition-all duration-300 hover:scale-105 hover:-translate-y-2 card-ocean">
              <div className="w-14 h-14 bg-gradient-to-br from-cyan-400 to-teal-400 rounded-2xl flex items-center justify-center mb-4 text-3xl shadow-lg group-hover:animate-float group-hover:shadow-cyan-400/50">
                🗺️
              </div>
              <h3 className="text-xl font-bold text-gray-900 dark:text-white mb-3 group-hover:text-cyan-600 dark:group-hover:text-cyan-400 transition-colors">AI Study Maps</h3>
              <p className="text-gray-600 dark:text-gray-400 leading-relaxed">
                Chart your course with personalized daily study plans generated by AI navigation.
              </p>
            </div>

            {/* Feature 2 - Ship Fleet */}
            <div className="group p-8 rounded-2xl bg-gradient-to-br from-teal-50 to-emerald-50 dark:from-teal-900/20 dark:to-emerald-900/20 border border-teal-200 dark:border-teal-800 hover:shadow-2xl hover:shadow-teal-500/20 transition-all duration-300 hover:scale-105 hover:-translate-y-2 card-ocean">
              <div className="w-14 h-14 bg-gradient-to-br from-teal-400 to-emerald-400 rounded-2xl flex items-center justify-center mb-4 text-3xl shadow-lg group-hover:animate-drift group-hover:shadow-teal-400/50">
                ⛵
              </div>
              <h3 className="text-xl font-bold text-gray-900 dark:text-white mb-3 group-hover:text-teal-600 dark:group-hover:text-teal-400 transition-colors">Class Fleet</h3>
              <p className="text-gray-600 dark:text-gray-400 leading-relaxed">
                Organize your classes like ships in a fleet. Track assignments and never miss a deadline.
              </p>
            </div>

            {/* Feature 3 - Treasure Chest */}
            <div className="group p-8 rounded-2xl bg-gradient-to-br from-amber-50 to-yellow-50 dark:from-amber-900/20 dark:to-yellow-900/20 border border-amber-200 dark:border-amber-800 hover:shadow-2xl hover:shadow-amber-500/20 transition-all duration-300 hover:scale-105 hover:-translate-y-2 card-ocean">
              <div className="w-14 h-14 bg-gradient-to-br from-amber-400 to-yellow-400 rounded-2xl flex items-center justify-center mb-4 text-3xl shadow-lg group-hover:animate-bounce group-hover:shadow-amber-400/50">
                💰
              </div>
              <h3 className="text-xl font-bold text-gray-900 dark:text-white mb-3 group-hover:text-amber-600 dark:group-hover:text-amber-400 transition-colors">Grade Treasure</h3>
              <p className="text-gray-600 dark:text-gray-400 leading-relaxed">
                Track your grades like precious treasure. Calculate GPA and monitor your progress.
              </p>
            </div>

            {/* Feature 4 - Tidal Calendar */}
            <div className="group p-8 rounded-2xl bg-gradient-to-br from-sky-50 to-blue-50 dark:from-sky-900/20 dark:to-blue-900/20 border border-sky-200 dark:border-sky-800 hover:shadow-2xl hover:shadow-sky-500/20 transition-all duration-300 hover:scale-105 hover:-translate-y-2 card-ocean">
              <div className="w-14 h-14 bg-gradient-to-br from-sky-400 to-blue-400 rounded-2xl flex items-center justify-center mb-4 text-3xl shadow-lg group-hover:animate-wave group-hover:shadow-sky-400/50">
                🌙
              </div>
              <h3 className="text-xl font-bold text-gray-900 dark:text-white mb-3 group-hover:text-sky-600 dark:group-hover:text-sky-400 transition-colors">Tidal Calendar</h3>
              <p className="text-gray-600 dark:text-gray-400 leading-relaxed">
                Visualize your schedule like ocean tides. See all assignments and events at a glance.
              </p>
            </div>

            {/* Feature 5 - Memory Reef */}
            <div className="group p-8 rounded-2xl bg-gradient-to-br from-violet-50 to-purple-50 dark:from-violet-900/20 dark:to-purple-900/20 border border-violet-200 dark:border-violet-800 hover:shadow-2xl hover:shadow-violet-500/20 transition-all duration-300 hover:scale-105 hover:-translate-y-2 card-ocean">
              <div className="w-14 h-14 bg-gradient-to-br from-violet-400 to-purple-400 rounded-2xl flex items-center justify-center mb-4 text-3xl shadow-lg group-hover:animate-float group-hover:shadow-violet-400/50">
                🪸
              </div>
              <h3 className="text-xl font-bold text-gray-900 dark:text-white mb-3 group-hover:text-violet-600 dark:group-hover:text-violet-400 transition-colors">Memory Reef</h3>
              <p className="text-gray-600 dark:text-gray-400 leading-relaxed">
                Auto-generate flashcards and study guides from your notes with AI coral magic.
              </p>
            </div>

            {/* Feature 6 - Lighthouse Alerts */}
            <div className="group p-8 rounded-2xl bg-gradient-to-br from-rose-50 to-pink-50 dark:from-rose-900/20 dark:to-pink-900/20 border border-rose-200 dark:border-rose-800 hover:shadow-2xl hover:shadow-rose-500/20 transition-all duration-300 hover:scale-105 hover:-translate-y-2 card-ocean">
              <div className="w-14 h-14 bg-gradient-to-br from-rose-400 to-pink-400 rounded-2xl flex items-center justify-center mb-4 text-3xl shadow-lg group-hover:pulse-glow group-hover:shadow-rose-400/50">
                🗼
              </div>
              <h3 className="text-xl font-bold text-gray-900 dark:text-white mb-3 group-hover:text-rose-600 dark:group-hover:text-rose-400 transition-colors">Lighthouse Alerts</h3>
              <p className="text-gray-600 dark:text-gray-400 leading-relaxed">
                Get timely beacon signals for upcoming due dates, tests, and study sessions.
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* How It Works Section */}
      <section className="py-20 px-4 sm:px-6 lg:px-8 bg-gradient-to-br from-cyan-50 to-teal-50 dark:from-slate-900 dark:to-cyan-950">
        <div className="max-w-7xl mx-auto">
          <div className="text-center mb-16">
            <span className="text-4xl mb-4 block">⚓</span>
            <h2 className="text-3xl sm:text-4xl font-bold text-gray-900 dark:text-white mb-4">
              Set Sail in Minutes
            </h2>
            <p className="text-lg text-gray-600 dark:text-gray-400 max-w-2xl mx-auto">
              Three simple steps to begin your academic voyage.
            </p>
          </div>

          <div className="grid md:grid-cols-3 gap-8">
            <div className="text-center group">
              <div className="w-16 h-16 bg-gradient-to-br from-cyan-500 to-teal-500 text-white text-2xl font-bold rounded-2xl flex items-center justify-center mx-auto mb-4 shadow-lg group-hover:scale-110 transition-transform">
                🚢
              </div>
              <h3 className="text-xl font-semibold text-gray-900 dark:text-white mb-2">Board the Ship</h3>
              <p className="text-gray-600 dark:text-gray-400">
                Sign up with Google in seconds. No treasure required.
              </p>
            </div>
            <div className="text-center group">
              <div className="w-16 h-16 bg-gradient-to-br from-teal-500 to-emerald-500 text-white text-2xl font-bold rounded-2xl flex items-center justify-center mx-auto mb-4 shadow-lg group-hover:scale-110 transition-transform">
                🗺️
              </div>
              <h3 className="text-xl font-semibold text-gray-900 dark:text-white mb-2">Chart Your Course</h3>
              <p className="text-gray-600 dark:text-gray-400">
                Add your classes, set your schedule, and mark your destinations.
              </p>
            </div>
            <div className="text-center group">
              <div className="w-16 h-16 bg-gradient-to-br from-emerald-500 to-cyan-500 text-white text-2xl font-bold rounded-2xl flex items-center justify-center mx-auto mb-4 shadow-lg group-hover:scale-110 transition-transform">
                🌊
              </div>
              <h3 className="text-xl font-semibold text-gray-900 dark:text-white mb-2">Ride the Waves</h3>
              <p className="text-gray-600 dark:text-gray-400">
                Let AI navigate your studies and reach every destination on time.
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* Success Metrics - Ocean themed */}
      <section className="py-20 px-4 sm:px-6 lg:px-8 bg-gradient-to-br from-cyan-600 via-teal-600 to-emerald-600 relative overflow-hidden">
        {/* Animated wave decoration */}
        <div className="absolute top-0 left-0 w-full h-20 opacity-20 animate-pulse">
          <svg viewBox="0 0 1200 120" preserveAspectRatio="none" className="w-full h-full">
            <path d="M321.39,56.44c58-10.79,114.16-30.13,172-41.86,82.39-16.72,168.19-17.73,250.45-.39C823.78,31,906.67,72,985.66,92.83c70.05,18.48,146.53,26.09,214.34,3V0H0V27.35A600.21,600.21,0,0,0,321.39,56.44Z" fill="white"/>
          </svg>
        </div>

        <div className="max-w-6xl mx-auto relative z-10">
          <div className="text-center mb-12">
            <span className="text-6xl mb-4 block animate-bounce">🏆</span>
            <h2 className="text-3xl sm:text-4xl font-bold text-white mb-4">
              Students Are Achieving More
            </h2>
            <p className="text-cyan-100 text-lg">Real results from students using StudyTide</p>
          </div>

          <div className="grid md:grid-cols-3 gap-8">
            <div className="text-center p-8 bg-white/10 backdrop-blur-md rounded-2xl border border-white/20 hover:bg-white/15 transition-all hover:scale-105 hover:shadow-xl">
              <div className="text-6xl font-bold text-white mb-3">85%</div>
              <div className="text-cyan-100 text-lg font-medium">Report Better Grades</div>
              <div className="text-cyan-200 text-sm mt-2">After 1 semester</div>
            </div>
            <div className="text-center p-8 bg-white/10 backdrop-blur-md rounded-2xl border border-white/20 hover:bg-white/15 transition-all hover:scale-105 hover:shadow-xl">
              <div className="text-6xl font-bold text-white mb-3">90%</div>
              <div className="text-cyan-100 text-lg font-medium">Feel More Organized</div>
              <div className="text-cyan-200 text-sm mt-2">Within first month</div>
            </div>
            <div className="text-center p-8 bg-white/10 backdrop-blur-md rounded-2xl border border-white/20 hover:bg-white/15 transition-all hover:scale-105 hover:shadow-xl">
              <div className="text-6xl font-bold text-white mb-3">3hrs</div>
              <div className="text-cyan-100 text-lg font-medium">Time Saved Weekly</div>
              <div className="text-cyan-200 text-sm mt-2">Through smart planning</div>
            </div>
          </div>
        </div>
      </section>

      {/* CTA Section - Ocean themed */}
      <section className="py-20 px-4 sm:px-6 lg:px-8 relative">
        <div className="absolute inset-0 bg-gradient-to-br from-sky-100/50 to-cyan-100/50 dark:from-cyan-900/20 dark:to-teal-900/20"></div>
        <div className="max-w-4xl mx-auto text-center relative z-10">
          <span className="text-5xl mb-4 block animate-float">⛵</span>
          <h2 className="text-3xl sm:text-4xl font-bold text-gray-900 dark:text-white mb-4">
            Ready to Set Sail?
          </h2>
          <p className="text-lg text-gray-600 dark:text-gray-400 mb-8">
            Join thousands of sailors navigating their academic journey with StudyTide.
          </p>
          <Link href="/signup" className="inline-flex items-center gap-2 px-8 py-4 bg-gradient-to-r from-cyan-500 to-teal-500 text-white font-semibold rounded-xl hover:from-cyan-600 hover:to-teal-600 transition-all hover:shadow-lg hover:shadow-cyan-500/25 transform hover:scale-105">
            <span>🌊</span>
            Begin Your Voyage
            <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 7l5 5m0 0l-5 5m5-5H6" />
            </svg>
          </Link>
          <p className="mt-4 text-sm text-gray-500 dark:text-gray-400">
            🐚 No treasure required • Free forever for basic features
          </p>
        </div>
      </section>

      {/* Footer - Ocean themed */}
      <footer className="py-12 px-4 sm:px-6 lg:px-8 bg-gradient-to-r from-cyan-900 via-teal-900 to-emerald-900 text-white">
        <div className="max-w-7xl mx-auto">
          <div className="flex flex-col md:flex-row justify-between items-center gap-6">
            <div className="flex items-center gap-2">
              <span className="text-2xl">🌊</span>
              <span className="text-lg font-bold">
                Study<span className="text-cyan-300">Tide</span>
              </span>
            </div>
            <div className="flex items-center gap-6 text-sm text-cyan-200">
              <a href="#" className="hover:text-white transition-colors">About</a>
              <a href="#features" className="hover:text-white transition-colors">Features</a>
              <a href="#" className="hover:text-white transition-colors">Privacy</a>
              <a href="#" className="hover:text-white transition-colors">Terms</a>
            </div>
            <div className="text-sm text-cyan-300">
              © 2025 StudyTide. Smooth sailing ahead! 🐬
            </div>
          </div>
        </div>
      </footer>
    </div>
  );
}
